### ISSUE TITLE
Preview image on hover

### ISSUE THREAD

**Issue by R3uan3** [viacheslav-lozinskyi/Preview-HTML#2]
Is it possible somehow to preview an image when hovered?
I mean something similar to this extension: 

https://marketplace.visualstudio.com/items?itemName=MadsKristensen.HtmlTools&ssr=false

![image](https://github.com/viacheslav-lozinskyi/Preview-HTML/assets/103058225/9614a889-3ea1-44ad-a3ee-f64d5a9c775e)

The mentioned extension didn't work on VS22.

**Comment by viacheslav-lozinskyi** [comment]
I think you need "HTML Tools 2022".
Seems this extension not ported by [Mads Kristensen](https://marketplace.visualstudio.com/publishers/MadsKristensen) yet.
Therefore better to ask him about plans with porting of this tool.

Preview-HTML doesn't work as "HTML Tools".
It's only HTML preview in MetaOutput, and I don't plan to make direct competitor of this tool.

**Comment by R3uan3** [comment]
To be honest i was searching just for a way to preview a image when its hovered.

Mads will not update it to VS22 because the extension depends on another extension that he uses and no long worker on VS22 because of some apis got removed.

**Comment by viacheslav-lozinskyi** [comment]
I think you have to continue search necessary extension in VS Marketplace.
There lot of extensions, and should be something that you need.
